services:
  downstream:
    image: wiremock/wiremock:3.13.2-3
    volumes:
      - ./tests/WireMock/mappings:/home/wiremock/mappings:ro

  proxy:
    build: .
    ports:
      - "8085:8085"
    volumes:
      - ./tests/Shuttering/Pages/shuttered-proxy.html:/app/Shuttering/Pages/shuttered-proxy.html:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AWS_EMF_ENABLED: false
      PORT: 8085
      Health__All__ApiKey: ApiKey
      ReverseProxy__Clusters__RegulatorsWasteDashboard__Destinations__Primary__Address: http://downstream:8080/
      ReverseProxy__Clusters__RegulatorsCertificatesOfCompliance__Destinations__Primary__Address: http://downstream:8080/
      ReverseProxy__Routes__ShutteredProxy__ClusterId: ShutteredProxy
      ReverseProxy__Routes__ShutteredProxy__Match__Path: "/shuttered-proxy/{**catch-all}"
      ReverseProxy__Routes__ShutteredProxy__Metadata__Shuttered: true
      ReverseProxy__Clusters__ShutteredProxy__Destinations__Primary__Address: http://downstream:8080/
    depends_on:
      downstream:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8085/health"]
      interval: 2s
      timeout: 5s
      retries: 10
